<!doctype html>

<html>
<head>
    <meta charset="utf-8">

    <title>Zadanie1</title>
    <style>
        textarea{
            width: 500px;
            height: 200px;
        }

    </style>
</head>

<body>

    <form action = "ch.php" method="post">
        <textarea name = "inputText">Lorem ipsum dolor sit amet, urwana szmawato consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ornare quam viverra orci sagittis. Ultricies leo integer malesuada nunc vel risus. Nisl vel pretium lectus quam id leo. Mus mauris vitae ultricies leo integer malesuada nunc. Eleifend donec pretium vulputate sapien nec sagittis aliquam. Consequat interdum varius sit amet. Integer vitae justo eget magna fermentum iaculis eu. Do urwanego jego macRisus quis varius quam quisque id diam vel. Aenean et tortor at risus. Arcu risus quis varius quam quisque id diam. Blandit libero volutpat sed cras ornare arcu dui.

        Przyolera jasna Nullam ac tortor vitae purus. Cras adipiscing enim eu turpis egestas pretium aenean. Fames ac turpis egestas sed tempus urna. Porta non pulvinar neque laoreet suspendisse interdum. Varius sit amet mattis vulputate enim nulla aliquet. Neque volutpat ac tincidunt vitae. Suspendisse ultrices gravida dictum fusce. Porttitor lacus luctus accumsan tortor posuere ac ut. Facilisis sed odio morbi quis commodo odio aenean sed adipiscing. Sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae. Massa massa ultricies mi quis hendrerit dolor magna eget. Et leo duis ut diam quam nulla porttitor. Adipiscing commodo elit at imperdiet dui accumsan sit. Turpis massa tincidunt dui ut. Nunc consequat interdum varius sit amet mattis vulputate. Mattis rhoncus urna neque viverra justo nec ultrices dui. Arcu odio ut sem nulla pharetra diam sit amet nisl. Mauris cursus mattis molestie a iaculis. Lorem ipsum dolor sit amet.

        Elementum curabitur vitae nunc sed. At volutpat diam ut venenatis tellus in metus vulputate. Dui ut ornare lectus sit amet est placerat in egestas. Vitae congue mauris rhoncus aenean vel. Orci nulla pellentesque dignissim enim. Odio ut sem nulla pharetra diam sit. Maecenas accumsan lacus vel facilisis volutpat est velit. Nibh venenatis cras sed felis eget velit aliquet. Neque sodales ut etiam sit amet nisl purus in mollis. Eget aliquet nibh praesent tristique magna sit amet. Aliquet sagittis id consectetur purus. Nulla malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Nulla facilisi etiam dignissim diam quis enim. Placerat duis ultricies lacus sed. Dictum sit amet justo donec enim diam vulputate ut. Dictum at tempor commodo ullamcorper a lacus vestibulum. Convallis tellus id interdum velit laoreet. Turpis nunc eget lorem dolor. Accumsan lacus vel facilisis volutpat est velit egestas dui id.

        Urna porttitor rhoncus dolor purus non enim praesent elementum. Imperdiet proin fermentum leo vel. Auctor elit sed vulputate mi sit. Molestie at elementum eu facilisis sed odio morbi quis. Vitae elementum curabitur vitae nunc sed velit dignissim. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. A pellentesque sit amet porttitor eget dolor morbi non arcu. Amet mattis vulputate enim nulla aliquet porttitor lacus luctus. Ut sem nulla pharetra diam sit amet. Phasellus egestas tellus rutrum tellus pellentesque. Eu feugiat pretium nibh ipsum consequat. Urna nunc id cursus metus aliquam eleifend mi. Mi bibendum neque egestas congue quisque egestas diam in arcu. Adipiscing tristique risus nec feugiat in fermentum. Eget nunc lobortis mattis aliquam faucibus purus in massa.

        Dolor sit amet consectetur adipiscing elit ut aliquam purus. Ultricies integer quis auctor elit sed vulputate mi sit. Risus pretium quam vulputate dignissim suspendisse in est. Vel quam elementum pulvinar etiam non quam. Varius duis at consectetur lorem donec massa sapien. Amet porttitor eget dolor morbi non arcu risus quis varius. Cras pulvinar mattis nunc sed blandit libero volutpat. Nunc lobortis mattis aliquam faucibus purus in massa tempor nec. Malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Bibendum enim facilisis gravida neque convallis a cras semper auctor. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus.

        Tempor orci dapibus ultrices in iaculis nunc. Tortor consequat id porta nibh venenatis cras sed felis eget. Quam vulputate dignissim suspendisse in est ante. Amet dictum sit amet justo donec enim diam vulputate. Maecenas ultricies mi eget mauris pharetra. Erat imperdiet sed euismod nisi porta. Velit dignissim sodales ut eu sem integer vitae. Lectus magna fringilla urna porttitor. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Nunc congue nisi vitae suscipit tellus mauris. Viverra maecenas accumsan lacus vel facilisis volutpat est. Vulputate mi sit amet mauris commodo quis. At tellus at urna condimentum mattis pellentesque id nibh.

        Ac ut consequat semper viverra nam libero. Ipsum dolor sit amet consectetur adipiscing elit. Elementum tempus egestas sed sed risus. In massa tempor nec feugiat. Elit pellentesque habitant morbi tristique senectus et netus et. Vitae semper quis lectus nulla at. Sit amet commodo nulla facilisi nullam vehicula ipsum a arcu. Suspendisse interdum consectetur libero id faucibus. Pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum. Dignissim enim sit amet venenatis. Leo a diam sollicitudin tempor id eu nisl nunc mi. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Fringilla ut morbi tincidunt augue interdum velit euismod in. Est lorem ipsum dolor sit amet consectetur adipiscing. Sed vulputate odio ut enim blandit volutpat maecenas volutpat blandit.

        Non odio euismod lacinia at quis risus sed vulputate. Consequat interdum varius sit amet mattis vulputate enim nulla aliquet. Pellentesque habitant morbi tristique senectus et. Orci phasellus egestas tellus rutrum tellus. Augue neque gravida in fermentum et sollicitudin. Ac ut consequat semper viverra nam libero justo. Facilisis volutpat est velit egestas dui id ornare. Sit amet porttitor eget dolor morbi non arcu risus. Ipsum dolor sit amet consectetur. Adipiscing enim eu turpis egestas pretium aenean. Mi eget mauris pharetra et. Elit pellentesque habitant morbi tristique senectus et netus. Pellentesque pulvinar pellentesque habitant morbi tristique. Lacinia at quis risus sed vulputate odio. Urna neque viverra justo nec ultrices. Cursus metus aliquam eleifend mi in nulla.

        Cras pulvinar mattis nunc sed. Justo donec enim diam vulputate ut pharetra sit amet aliquam. Hendrerit dolor magna eget est lorem ipsum. Suspendisse sed nisi lacus sed viverra tellus. In iaculis nunc sed augue lacus viverra vitae. Arcu non sodales neque sodales. Nunc scelerisque viverra mauris in aliquam sem fringilla ut. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat. Tincidunt id aliquet risus feugiat in ante. Sit amet risus nullam eget felis eget nunc. Cursus in hac habitasse platea dictumst quisque sagittis. Dolor sed viverra ipsum nunc. Nulla facilisi cras fermentum odio. Nisi vitae suscipit tellus mauris a. Id cursus metus aliquam eleifend.

        Imperdiet proin fermentum leo vel. A scelerisque purus semper eget duis at tellus at. Tempus iaculis urna id volutpat lacus. Amet porttitor eget dolor morbi non. Massa sapien faucibus et molestie ac feugiat. Elit at imperdiet dui accumsan sit amet nulla. Morbi enim nunc faucibus a pellentesque. Duis ultricies lacus sed turpis tincidunt id. In arcu cursus euismod quis viverra nibh cras pulvinar. Aliquam etiam erat velit scelerisque in dictum non consectetur a. Congue nisi vitae suscipit tellus mauris a diam maecenas. Mollis aliquam ut porttitor leo a diam.

        Ornare arcu odio ut sem. Eu ultrices vitae auctor eu augue ut. Lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque. Adipiscing enim eu turpis egestas. Turpis cursus in hac habitasse platea dictumst. Justo laoreet sit amet cursus sit amet dictum. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim. Eget dolor morbi non arcu risus quis. Id faucibus nisl tincidunt eget nullam non nisi est sit. Vitae congue mauris rhoncus aenean vel elit. Nam at lectus urna duis convallis convallis. Sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus. Tristique senectus et netus et malesuada fames ac turpis egestas. Tristique et egestas quis ipsum suspendisse ultrices. Mi eget mauris pharetra et ultrices neque. Etiam dignissim diam quis enim. Diam in arcu cursus euismod quis viverra. Cursus risus at ultrices mi tempus. Gravida cum sociis natoque penatibus et magnis dis parturient montes. In ornare quam viverra orci sagittis eu.

        Augue mauris augue neque gravida in fermentum et sollicitudin ac. Posuere morbi leo urna molestie at. Viverra vitae congue eu consequat. Vitae congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. At lectus urna duis convallis. Nulla facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Ac tincidunt vitae semper quis. Vulputate mi sit amet mauris. A condimentum vitae sapien pellentesque habitant. Nibh tellus molestie nunc non blandit massa. Lectus sit amet est placerat. Leo duis ut diam quam nulla porttitor massa. Porta nibh venenatis cras sed felis eget velit.

        Elementum eu facilisis sed odio morbi. Pellentesque sit amet porttitor eget dolor. Etiam sit amet nisl purus in. Sem fringilla ut morbi tincidunt augue interdum velit. Egestas diam in arcu cursus euismod quis viverra. Venenatis a condimentum vitae sapien pellentesque habitant morbi tristique. Dui ut ornare lectus sit amet est. Arcu vitae elementum curabitur vitae nunc sed velit dignissim sodales. Nulla pellentesque dignissim enim sit amet venenatis. Non arcu risus quis varius quam quisque id diam vel. Sit amet purus gravida quis.

        Lacinia quis vel eros donec ac odio tempor orci dapibus. A diam sollicitudin tempor id eu nisl nunc. Nulla posuere sollicitudin aliquam ultrices sagittis orci. Velit sed ullamcorper morbi tincidunt ornare. Tellus cras adipiscing enim eu turpis egestas. Fames ac turpis egestas sed tempus urna et. Vitae sapien pellentesque habitant morbi tristique senectus et netus. Tempor orci eu lobortis elementum. Purus ut faucibus pulvinar elementum integer. In hac habitasse platea dictumst vestibulum. Pretium quam vulputate dignissim suspendisse in.

        Donec ac odio tempor orci dapibus. Integer feugiat scelerisque varius morbi enim nunc faucibus a pellentesque. Pretium vulputate sapien nec sagittis aliquam. Purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Venenatis urna cursus eget nunc scelerisque. Tincidunt augue interdum velit euismod in pellentesque massa. Purus non enim praesent elementum facilisis leo vel fringilla. Pulvinar neque laoreet suspendisse interdum consectetur libero id. Sollicitudin tempor id eu nisl nunc mi. Praesent semper feugiat nibh sed pulvinar. Nisl nunc mi ipsum faucibus vitae aliquet nec. Quam vulputate dignissim suspendisse in est ante.

        Adipiscing tristique risus nec feugiat. Blandit cursus risus at ultrices mi tempus. Aliquet risus feugiat in ante metus dictum at tempor. Mattis aliquam faucibus purus in massa tempor nec. Eget mauris pharetra et ultrices neque ornare aenean euismod elementum. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Netus et malesuada fames ac turpis egestas. Cras fermentum odio eu feugiat. Placerat vestibulum lectus mauris ultrices eros in cursus turpis massa. Id faucibus nisl tincidunt eget nullam. Ornare suspendisse sed nisi lacus sed. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce. Amet justo donec enim diam vulputate. Sed risus pretium quam vulputate. Tellus at urna condimentum mattis. Ultrices in iaculis nunc sed augue lacus viverra vitae.

        Odio tempor orci dapibus ultrices in iaculis nunc. Amet commodo nulla facilisi nullam vehicula ipsum a arcu. Urna id volutpat lacus laoreet non curabitur gravida. Elit scelerisque mauris pellentesque pulvinar. Bibendum at varius vel pharetra vel turpis nunc. Turpis egestas maecenas pharetra convallis. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at augue. Et ultrices neque ornare aenean euismod elementum nisi quis eleifend. Lectus nulla at volutpat diam. Quisque sagittis purus sit amet volutpat consequat mauris. Consectetur libero id faucibus nisl tincidunt. Non enim praesent elementum facilisis leo. Faucibus interdum posuere lorem ipsum.

        Purus sit amet volutpat consequat. Vivamus at augue eget arcu dictum varius duis at. Volutpat sed cras ornare arcu dui. Est lorem ipsum dolor sit. Non blandit massa enim nec dui nunc mattis enim ut. Euismod quis viverra nibh cras pulvinar mattis nunc. Fringilla urna porttitor rhoncus dolor purus non enim praesent elementum. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Quisque non tellus orci ac auctor. Arcu dui vivamus arcu felis bibendum ut tristique et egestas. At consectetur lorem donec massa sapien faucibus et. Faucibus et molestie ac feugiat sed. Nunc faucibus a pellentesque sit amet porttitor. Vel turpis nunc eget lorem dolor sed. Sapien pellentesque habitant morbi tristique senectus. Arcu felis bibendum ut tristique et egestas quis ipsum suspendisse. Tortor consequat id porta nibh venenatis cras sed felis. Dlaczego to urwy Felis donec et odio pellentesque diam volutpat. Lectus nulla at volutpat diam ut venenatis tellus in metus.

        Non tellus orci ac auctor augue mauris augue neque gravida. Aenean vel elit scelerisque mauris pellentesque. Cursus risus at ultrices mi tempus imperdiet nulla. Sed vulputate odio ut enim. Iaculis eu non diam phasellus vestibulum lorem sed risus. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor magna. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien et. Non tellus orci ac auctor augue mauris augue neque gravida. Gravida in fermentum et sollicitudin ac orci phasellus. Sollicitudin tempor id eu nisl nunc mi ipsum faucibus. Molestie at elementum eu facilisis sed odio morbi quis. Viverra maecenas accumsan lacus vel facilisis volutpat. Mauris nunc congue nisi vitae. Sed id semper risus in hendrerit gravida rutrum quisque. Tellus orci ac auctor augue. Libero volutpat sed cras ornare arcu dui vivamus arcu felis. Wolera Ac ut consequat semper viverra nam libero justo laoreet sit.

        Feugiat pretium nibh ipsum consequat nisl vel pretium. Vestibulum lectus mauris ultrices eros in. Dolor morbi non arcu risus quis varius quam quisque id. Consectetur purus ut faucibus pulvinar elementum integer enim neque volutpat. Dolor magna eget est lorem. Id faucibus nisl tincidunt eget nullam non. Suspendisse in est ante in nibh mauris cursus. Integer enim neque volutpat ac. Blandit libero volutpat sed cras ornare arcu dui vivamus arcu. Ullamcorper malesuada proin libero nunc consequat. Amet dictum sit amet justo. Est lorem ipsum dolor sit amet consectetur. Eleifend donec pretium vulputate sapien nec sagittis. Po jakiego warurwa oluja Mauris augue neque gravida in fermentum. Bibendum enim facilisis gravida neque convallis a cras semper. Scelerisque viverra mauris in aliquam sem fringilla ut morbi tincidunt. Id leo in vitae turpis massa sed elementum tempus. Risus nullam eget felis eget nunc lobortis mattis. Risus sed vulputate odio ut. Egestas integer eget aliquet nibh. Wypierdowaszony</textarea><br>
        <input type = "text" name = "find" placeholder = "Szukany ciąg"><br>
        <input type = "submit">
    </form>

</body>
</html>

